const cards=document.getElementById('cards');
const rows=document.getElementById('compareRows');
const search=document.getElementById('search');
const resultCount=document.getElementById('resultCount');
let activeFilter='all';
const mark=v=>v==='Yes'?'<span class="yes">✓ Yes</span>':v==='Partial'?'<span class="partial">~ Partial</span>':v==='Reference'||v==='Derived'?'<span class="reference">◆ '+v+'</span>':v;
const matches=(x,q)=>{const hay=[x.name,x.description,x.badge,...x.tags].join(' ').toLowerCase();return !q||hay.includes(q.toLowerCase());};
const filtered=()=>KUNDALI_MAKERS.filter(x=>(activeFilter==='all'||x.tags.includes(activeFilter))&&matches(x,search.value));
function render(){const list=filtered();resultCount.textContent=`${list.length} resource${list.length===1?'':'s'}`;cards.innerHTML='';rows.innerHTML='';list.forEach((x,i)=>{cards.insertAdjacentHTML('beforeend',`<article class="card" style="--i:${i}"><div class="card-top"><div class="logo">${x.initial}</div><span class="badge">${x.badge}</span></div><h3>${x.name}</h3><p>${x.description}</p><div class="tags">${x.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><a class="card-link" href="${x.url}" target="_blank" rel="noopener noreferrer">Open resource <span>↗</span></a></article>`);rows.insertAdjacentHTML('beforeend',`<tr><td><strong>${x.name}</strong></td><td>${mark(x.d1)}</td><td>${mark(x.d9)}</td><td>${mark(x.degrees)}</td><td>${mark(x.nakshatra)}</td><td>${mark(x.dasha)}</td><td>${x.transparency}</td></tr>`);});if(!list.length)cards.innerHTML='<div class="empty"><b>No matching resource</b><span>Try another search or filter.</span></div>';}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render();}));search.addEventListener('input',render);
const form=document.getElementById('birthForm'),output=document.getElementById('profileOutput'),copyBtn=document.getElementById('copyProfile'),clearBtn=document.getElementById('clearProfile'),compareLinks=document.getElementById('compareLinks'),linkButtons=document.getElementById('linkButtons');let profileText='';
function buildProfile(){const name=document.getElementById('birthName').value.trim(),system=document.getElementById('dateSystem').value,date=document.getElementById('birthDate').value.trim(),time=document.getElementById('birthTime').value,place=document.getElementById('birthPlace').value.trim();profileText=[name&&`Name: ${name}`,`Date system: ${system}`,`Birth date: ${date}`,`Birth time: ${time}`,`Birth place: ${place}`].filter(Boolean).join('\n');output.innerHTML=`<strong>${date} · ${time}</strong><span>${place}${name?` · ${name}`:''}</span><small>${system} date input</small>`;copyBtn.disabled=false;compareLinks.hidden=false;linkButtons.innerHTML=KUNDALI_MAKERS.filter(x=>x.name!=='Swiss Ephemeris').map(x=>`<a href="${x.url}" target="_blank" rel="noopener noreferrer">${x.initial} ${x.name} ↗</a>`).join('');}
form.addEventListener('submit',e=>{e.preventDefault();buildProfile();document.getElementById('compare-mode').scrollIntoView({behavior:'smooth',block:'center'});});copyBtn.addEventListener('click',async()=>{if(!profileText)return;try{await navigator.clipboard.writeText(profileText);copyBtn.textContent='Copied ✓';setTimeout(()=>copyBtn.textContent='Copy birth data',1400);}catch{copyBtn.textContent='Select and copy manually';}});clearBtn.addEventListener('click',()=>{form.reset();profileText='';output.innerHTML='<strong>No profile yet</strong><span>Fill the form to generate a clean birth-data summary.</span>';copyBtn.disabled=true;copyBtn.textContent='Copy birth data';compareLinks.hidden=true;});
const verifyFields=[['Lagna / Ascendant','lagna'],['Sun sign','sun'],['Moon sign','moon'],['Mars sign','mars'],['Mercury sign','mercury'],['Jupiter sign','jupiter'],['Venus sign','venus'],['Saturn sign','saturn'],['Rahu / Ketu','nodes'],['Moon Nakshatra + Pada','nakshatra'],['Lagna degree','lagnaDeg'],['Moon degree','moonDeg'],['D9 Navamsa Lagna','d9Lagna'],['Vimshottari Mahadasha','dasha']];
const sources=['hp','kn','sp'],storageKey='laxman-kundali-verification-v1',norm=v=>v.trim().toLowerCase().replace(/\s+/g,' ').replace(/°/g,'').replace(/\s*\/\s*/g,'/');
function makeVerifyRows(){const tbody=document.getElementById('verifyRows');tbody.innerHTML=verifyFields.map(([label,key])=>`<tr><td><strong>${label}</strong></td>${sources.map(s=>`<td><input class="verify-input" data-source="${s}" data-key="${key}" placeholder="Enter result"></td>`).join('')}<td class="agreement-cell" data-agreement="${key}">—</td></tr>`).join('');document.querySelectorAll('.verify-input').forEach(i=>i.addEventListener('input',updateVerification));}
function updateVerification(){let comparable=0,agreed=0;verifyFields.forEach(([label,key])=>{const vals=sources.map(s=>document.querySelector(`[data-source="${s}"][data-key="${key}"]`).value).map(norm).filter(Boolean),cell=document.querySelector(`[data-agreement="${key}"]`);if(vals.length<2){cell.textContent='—';cell.className='agreement-cell';return;}comparable++;const unique=[...new Set(vals)];if(unique.length===1){agreed++;cell.textContent='✓ Match';cell.className='agreement-cell match';}else{cell.textContent='≠ Differ';cell.className='agreement-cell differ';}});const pct=comparable?Math.round(agreed/comparable*100):0;document.getElementById('agreementScore').textContent=`${pct}% agreement`;document.getElementById('verifySummary').innerHTML=comparable?`<b>${agreed} of ${comparable} comparable fields agree.</b><span>${pct===100?'All entered values match.':pct>=67?'Most entered values match; inspect the differences below.':pct>0?'Some values match, but calculation settings may differ.':'No entered fields agree yet.'}</span>`:'<b>Start entering results.</b><span>Agreement appears after at least two calculators contain a value for the same field.</span>';}
function verifyPayload(){return Object.fromEntries(document.querySelectorAll('.verify-input').map(i=>[`${i.dataset.source}.${i.dataset.key}`,i.value]));}function fillPayload(payload){document.querySelectorAll('.verify-input').forEach(i=>i.value=payload[`${i.dataset.source}.${i.dataset.key}`]||'');updateVerification();}
document.getElementById('loadDemo').addEventListener('click',()=>{const demo={};verifyFields.forEach(([label,key])=>sources.forEach(s=>demo[`${s}.${key}`]='Example'));demo['hp.lagna']='Aries';demo['kn.lagna']='Aries';demo['sp.lagna']='Taurus';demo['hp.lagnaDeg']='12.40';demo['kn.lagnaDeg']='12.40';demo['sp.lagnaDeg']='12.41';fillPayload(demo);});document.getElementById('clearVerify').addEventListener('click',()=>fillPayload({}));document.getElementById('saveVerify').addEventListener('click',()=>{localStorage.setItem(storageKey,JSON.stringify({savedAt:new Date().toISOString(),values:verifyPayload()}));const b=document.getElementById('saveVerify');b.textContent='Saved ✓';setTimeout(()=>b.textContent='Save locally',1400);});
makeVerifyRows();
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.values)fillPayload(saved.values);}catch{}
render();